version: "2"
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://172.18.0.2:27017/agree
  mongo:
    image: mongo:latest
